### ISSUE TITLE
CollectionView didSelectItemAt not being called

### ISSUE THREAD

**Issue by agarbowitzOmadaHealth** [shoheiyokoyama/Gemini#3]
Hello,

I've created a pull request here which shows a problem where didSelectItemAt in UICollectionViewDelegate is not being called when I use Gemini. 

Here is the link:

https://github.com/shoheiyokoyama/Gemini/pull/2

Does anyone else have this problem or knows how to work around this?

Thank you.

**Comment by shoheiyokoyama** [comment]
@agarbowitzOmadaHealth 
I resolve this problem and released version 1.1.2.
Thank you for reporting 👍
