### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by steve21124** [shoheiyokoyama/Gemini#4]
fyi: failing to compile in Swift 4
https://github.com/shoheiyokoyama/Gemini/blob/16529b218dffd7d4e13d20e4e9fc6a2c50c233d1/Gemini/GeminiAnimationModel.swift#L191

**Comment by shoheiyokoyama** [comment]
Hi @steve21124 

What is your Xcode version?

**Comment by steve21124** [comment]
Xcode 9 beta 4. I am closing this for now since I am not using gemini yet

**Comment by 4np** [comment]
Same for Version 9.0 beta 6 (9M214v)

Lifting ratio out seems to work, e.g.:

```
        let absoluteRatio = abs(ratio)
        let components = (0...3).map {
            (ec[$0] - sc[$0]) * absoluteRatio + sc[$0]
        }
```

**Comment by shoheiyokoyama** [comment]
I resolved this problem.  a293931b94e09ad5450be005309c78e8bc009567

@steve21124  @4np 
Thanks
