### ISSUE TITLE
swift 4 Compiler Error

### ISSUE THREAD

**Issue by alexookah** [shoheiyokoyama/Gemini#8]
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
![screen shot 2017-10-19 at 01 31 24](https://user-images.githubusercontent.com/9624843/31862565-ab37bc54-b748-11e7-95e3-acc165db26e7.png)

**Comment by alexookah** [comment]
plus some more warnings in swift 4:
YawRotationEffect line 16
Redundant conformance constraint 'Self': 'EasingAnimatable'

**Comment by shoheiyokoyama** [comment]
I fixed this warning.
[Delete redudant protocol](https://github.com/shoheiyokoyama/Gemini/commit/6d223150368f341f8886f0fe1bc5083751317111)

**Comment by alexookah** [comment]
@shoheiyokoyama 
what about the expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions. (check the 1st comment with screenshot)

**Comment by alexookah** [comment]
i see you have fixed the issues in the master repo. but you have not made any new release for the latest changes that fixes those issues.

**Comment by alexookah** [comment]
@shoheiyokoyama 
could you make the latest commit which fixes those issues in a release?

**Comment by shoheiyokoyama** [comment]
@Alexookah 
I just released version [1.2.0](https://github.com/shoheiyokoyama/Gemini/releases/tag/1.2.0)
Please install the latest version 👍

**Comment by alexookah** [comment]
@shoheiyokoyama  thanks will check it out! :)

**Comment by alexookah** [comment]
yeap no need to get updates with branch. thanks for releasing latest swift 4 fixes in the latest release. 1.2.0
